package modrinth

import (
	"errors"

	"github.com/mclucy/lucy/internal/knownpkgs"
	"github.com/mclucy/lucy/log"
	"github.com/mclucy/lucy/types"
	"github.com/mclucy/lucy/upstream"
)

// TODO: Refactor to separate all API functions to accept an url. While the urls
// are generated by other functions. This will make the code more modular and
// easier to test.

var (
	ErrNoVersion = errors.New("modrinth version not found")
	ErrNoProject = errors.New("modrinth project not found")
	ErrNoMember  = errors.New("modrinth project member not found")
)

// TODO: This has a chance of causing segmentation faults
func listVersions(slug types.BarePackageName) (
	versions []*versionResponse,
	err error,
) {
	tryFetch := func(target types.BarePackageName) (
		[]*versionResponse,
		error,
	) {
		var out []*versionResponse
		if err := requestJSON(
			versionsUrl(target),
			&out,
			ErrNoProject,
		); err != nil {
			return nil, err
		}
		return out, nil
	}

	versions, err = tryFetch(slug)
	if err == nil {
		return versions, nil
	}

	if canonical, ok := knownpkgs.Default().Session().Lookup(
		types.SourceModrinth,
		string(slug),
	); ok && canonical != string(slug) {
		return tryFetch(types.BarePackageName(canonical))
	}

	return nil, err
}

// getVersion is named as so because a Package in lucy is equivalent to a version
// in SourceModrinth.
func getVersion(
	local upstream.LocalContext,
	id types.VersionedPackageRef,
) (v *versionResponse, err error) {
	versions, err := listVersions(id.Name)
	if err != nil {
		return nil, err
	}
	if id.Version.CanInfer() {
		v, err = latestVersion(id.Name, id.Eco, local.GameVersion)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
	if selected := selectExactVersion(versions, id, local.GameVersion); selected != nil {
		return selected, nil
	}
	return nil, ErrNoVersion
}

func getVersionById(id string) (v *versionResponse, err error) {
	v = &versionResponse{}
	if err := requestJSON(versionUrl(id), v, ErrNoVersion); err != nil {
		return nil, err
	}
	return
}

func versionSupportsLoader(
	version *versionResponse,
	loader types.Ecosystem,
) bool {
	for _, l := range version.Loaders {
		if types.Ecosystem(l).Satisfy(loader) {
			return true
		}
	}
	return false
}

func latestVersion(
	slug types.BarePackageName,
	platform types.Ecosystem,
	gameVersion types.BareVersion,
) (v *versionResponse, err error) {
	versions, err := listVersions(slug)
	if err != nil {
		return nil, err
	}
	filterByLoader := platform != types.EcoUnspecified
	v, fellBack := selectLatestVersionByLoader(
		versions,
		platform,
		gameVersion,
		filterByLoader,
	)
	if v == nil {
		return nil, ErrNoVersion
	}
	if fellBack {
		log.Info("no release version found for " + slug.Title() + ", falling back to latest pre-release")
	}
	log.Debug("latest version of " + slug.String() + ": " + v.VersionNumber)
	return v, nil
}

func latestCompatibleVersion(
	slug types.BarePackageName,
	platform types.Ecosystem,
	gameVersion types.BareVersion,
) (v *versionResponse, err error) {
	versions, err := listVersions(slug)
	if err != nil {
		return nil, err
	}
	filterByLoader := platform != types.EcoUnspecified
	if filterByLoader {
		v, _ = selectLatestCompatibleVersionCandidate(
			versions,
			platform,
			gameVersion,
		)
	} else {
		v, _ = selectLatestVersionCandidate(versions, platform, gameVersion)
	}
	if v == nil {
		return nil, ErrNoVersion
	}
	if filterByLoader && latestReleaseVersion(
		versions,
		platform,
		gameVersion,
		true,
	) == nil {
		log.Info("no compatible version found for " + slug.Title() + ", falling back to latest pre-release")
	} else if !filterByLoader && latestReleaseVersion(
		versions,
		platform,
		gameVersion,
		false,
	) == nil {
		log.Info("no compatible version found for " + slug.Title() + ", falling back to latest pre-release")
	}
	return v, nil
}
