name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions: write-all

jobs:
  test:
    if: "!startsWith(github.event.head_commit.message, 'docs:') && !(github.event_name == 'pull_request' && startsWith(github.event.pull_request.title, 'docs:'))"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache: true

      - name: Set up Task
        uses: go-task/setup-task@v1
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Generate cipher files
        if: env.CF_API_KEY != ''
        run: task cipher-generate
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Run default checks
        run: task check
        
      - name: Generate coverage badge
        uses: ncruces/go-coverage-report@v0.3.2
        with:
          output-dir: dev
          badge-title: Coverage
          amend: true
